shelf/urls.py
from django.conf.urls import patterns, include, url

from shelf import views

urlpatterns = patterns('',
    url(r'^authors/$', views.AuthorListView.as_view(), name='author-list'),
    url(r'^authors/(?P<pk>\d+)/$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^books/$', views.BookListView.as_view(), name='book-list'),
    url(r'^books/(?P<pk>\d+)/$', views.BookDetailView.as_view(), name='book-detail'),
    )

stronka/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings 

from contact.views import MessageAddView
from shelf.views import MainPageView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shelf/', include('shelf.urls', namespace='shelf', app_name='shelf')),
    url(r'^contact/$', MessageAddView.as_view()),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', MainPageView.as_view(), name='main-page'),
]

contact/models.py
from django.db import models

class Message(models.Model):
    name=models.CharField(max_length=250)
    email=models.EmailField()
    message=models.TextField()
    
    def __str__(self):
        return "message from (name)".format(name=self.name)

rental/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.utils.timezone import now
from django.conf import settings

from shelf.models import BookItem
# Create your models here.

class Rental(models.Model):
    who = models.ForeignKey(settings.AUTH_USER_MODEL)
    what = models.ForeignKey(BookItem)
    when = models.DateTimeField(auto_now_add=True)
    returned=models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return "(who) rented (what)".format(who=self.who,
        what=self.what)

shelf/models.py
#from django.core.urlresolvers import reverse_lazy
from django.db import models

class Author(models.Model):
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=50)
    
    def __str__(self):
        return "{first_name} {last_name}".format(first_name=self.first_name,
            last_name=self.last_name)
    
    
class Publisher(models.Model):
    name=models.CharField(max_length=70)

    def __str__(self):
        return self.name


class BookCategory(models.Model):
    name=models.CharField(max_length=50)
    
    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors=models.ManyToManyField(Author)
    #author=models.ForeignKey(Author)
    categories=models.ManyToManyField(BookCategory)
    
    def __str__(self):
        return self.title
        
    #def get_absolute_url(self):
        #return reverse_lazy('shelf:book-detail', kwargs={'pk':self.id})


class BookEdition(models.Model):
    """
    Wydanie ksiązki
    """
    book=models.ForeignKey(Book)
    publisher=models.ForeignKey(Publisher)
    isbn=models.CharField(max_length=17)
    year=models.CharField(max_length=4, default='')
    
    def __str__(self):
        return"{book.title}, {publisher.name}".format(book=self.book,
        publisher=self.publisher)
    

class BookItem(models.Model):
    """
    Egzamplarz
    """
    edition=models.ForeignKey(BookEdition)
    catalogue_number=models.CharField(max_length=30)
    
    def __str__(self):
        return "{edition}".format(edition=self.edition)
        
    class Meta:
        #powinno znajdowac sie w aplikacji rental
        permissions = (
            ('can_rent', 'Can rent a book'),
            )
        
    
#tesndfnkjdsnjfs

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Permission
from django.db.models.signals import post_save
from django.dispatch import receiver
import logging

logger=logging.getLogger('django')

class User(AbstractUser):
    phone = models.CharField(max_length=15, blank=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    
    
    """def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        try:
            p=Permission.objects.get(codename='can_rent')
            self.user_permissions.add(p)
        except Exception as e:
            logger.log(logging.ERROR, "%s" % e)"""
        
        
    #signals
@receiver(post_save, sender=User)
def add_rent_permission(sender, *args, **kwargs):
    user = kwargs.get('instance')
    try:
        p=Permission.objects.get(codename='can_rent')
        user.user_permissions.add(p)
        logger.info("Permissions added")
    except Exception as e:
        logger.error("Error:Permission not added: %s" % e)

contact/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'message')
        

contact/views.py
from django.shortcuts import render
from django.views.generic import FormView, DetailView 

from .models import Message
from .forms import MessageForm

class MessageDetailView(DetailView):
    model = Message

class MessageAddView(FormView):
    form_class = MessageForm
    template_name = 'contact/message_form.html'
    sucess_url='/'
    
    #co jezeli dane beda poprawne 
    def form_valid(self, form):
        form.save()
        return super(MessageAddView, self).form_valid(form)
    

shelf/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView 

from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Author, Book

# Create your views here.

class MainPageView(TemplateView):
    template_name = 'index.html'
    
class AuthorListView(ListView):
    model = Author
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        super(AuthorListView, self).dispatch(*args, **kwargs)
    
class AuthorDetailView(DetailView):
    model = Author
    
class BookListView(ListView):
    model = Book
    
    
class BookDetailView(DetailView):
    model = Book
    

user/views.py
from django.shortcuts import render

# Create your views here.

contact/templates/contact/message_form.html
{% extends "base.html" %}

{%block content %}
<form method="post">
{% csrf_token %}  
    <table>
        {{form}}
</table>
<button type="submit">Send</button>
    </form>
{% endblock %}

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{%block content %}

<div><a href="{% url 'shelf:author-list' %}">Powrót do listy autorów</a></div>
Profil pisarza {{ object.last_name}} {{object.first_name}}

<h2>Lista książek autora</h2>
<ul>
{% for book in object.book_set.all %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }}</a> 
    </li>
{% endfor %}
</ul>
{% endblock %}

shelf/templates/shelf/author_list.html
{% extends "base.html" %}

{%block content %}

<ul>
{% for author in object_list %}
    <li><a href="{% url 'shelf:author-detail' author.id %}">{{author.first_name}} {{author.last_name}}</a></li>
{% endfor %}
</ul>

{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %} {% load shelf_tags %}

{%block content %}

<div><a href="{% url 'shelf:book-list' %}">Powrót do listy książek</a></div>
<div><a href="{% url 'shelf:author-list' %}">Powrót do listy autorów</a></div>
<h1>Opis książki {{ object.title}} </h1>

<h2>Wydania:</h2>
<ul>{% for edition in book.bookedition_set.all %}
<li>{{ edition.year|pub_date }} - {{ edition.publisher.name }}</li>

{% endfor %}</ul>
{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}

{% block content %}

<ul>
{% for book in book_list %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }}</a> - 
        {% for author in book.authors.all %}
            {{ author.first_name}} {{author.last_name}}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </li>
{% endfor %}
</ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load staticfiles %}
{% load socialaccount %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Book Rental{% endblock %}</title>
    {% bootstrap_css %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% providers_media_js %}
    <a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
    </br>
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body>
    {% bootstrap_messages %}
    <div style="margin: 20px">
        MAIN MENU: 
        {% if user.is_authenticated %} 
        <a href="{% url 'account_logout' %}">logout</a>
        {% else %}
        <a href="{% url 'account_login' %}">login</a>, <a href="{% url 'account_signup' %}">Register</a>
        {% endif %}
    </div>
        <img src="{% static "Books.jpg"%}" alt="book">
        {% block content %}
        
        {% endblock %}
    
</body>

</html>

templates/index.html
{% extends "base.html" %}

{%block content %}

<h1>MAIN PAGE</h1>
<ul>
    <li><a href="{% url 'shelf:book-list' %}">Lista wszyscy</a></li>
    <li><a href="{% url 'shelf:author-list' %}">Lista dla uzytkownikow</a></li>
</ul>
{% endblock %}

{% block title %}
Main page
{% endblock %}